//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DupliFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DupliFinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap del {
            get {
                object obj = ResourceManager.GetObject("del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicates found.
        /// </summary>
        internal static string msgNoDups {
            get {
                return ResourceManager.GetString("msgNoDups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        internal static string msgSure {
            get {
                return ResourceManager.GetString("msgSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string setCancel {
            get {
                return ResourceManager.GetString("setCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete &apos;{0}&apos; because it is in use; please check and see if the file is in use by any other program.  Select retry to attempt the delete again, or &quot;cancel&quot; to skip the delete..
        /// </summary>
        internal static string strFileInUse {
            get {
                return ResourceManager.GetString("strFileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File in use.
        /// </summary>
        internal static string strFileInUseHeader {
            get {
                return ResourceManager.GetString("strFileInUseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete &apos;{0}&apos; because it is read-only; please make the file writable.  Select retry to attempt the delete again, or cancel to skip the delete.
        /// </summary>
        internal static string strFileReadOnly {
            get {
                return ResourceManager.GetString("strFileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Read-Only.
        /// </summary>
        internal static string strFileReadOnlyHeader {
            get {
                return ResourceManager.GetString("strFileReadOnlyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levenshtein Distance.
        /// </summary>
        internal static string strLevenshtein {
            get {
                return ResourceManager.GetString("strLevenshtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading images from the disk.
        /// </summary>
        internal static string strLoading {
            get {
                return ResourceManager.GetString("strLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Absolute Error.
        /// </summary>
        internal static string strMAE {
            get {
                return ResourceManager.GetString("strMAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Squared Error.
        /// </summary>
        internal static string strMSE {
            get {
                return ResourceManager.GetString("strMSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean SSIM.
        /// </summary>
        internal static string strMSSIM {
            get {
                return ResourceManager.GetString("strMSSIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing comparision of image {0}.
        /// </summary>
        internal static string strProceessing {
            get {
                return ResourceManager.GetString("strProceessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sift.
        /// </summary>
        internal static string strSift {
            get {
                return ResourceManager.GetString("strSift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural SIMilarity (SSIM).
        /// </summary>
        internal static string strSSIM {
            get {
                return ResourceManager.GetString("strSSIM", resourceCulture);
            }
        }
    }
}
